version: '2'
services:
  ones_ws:
#    image: trantor77/ws-1c-apache22
    image: altf13/1c_server
    container_name: ones_ws
    hostname: ones_ws
    restart: always
    ports:
     - "80:80"
     - "1540-1541:1540-1541"
     - "1560-1591:1560-1591"
    volumes:
     - /volume1/docker/1c/pg_sql:/var/lib/postgresql/data
     - /volume1/docker/1c/data:/root/.1cv8
     - /volume1/docker/1c/apache2:/etc/apache2/
     - /volume1/docker/1c/html:/var/www/html
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: temrdm/1c_postgres
    container_name: postgres
    hostname: postgres
    restart: always
    ipc: host #при старте postgresql выдает ошибку про shmmax в sysctl. Это баг докера, он зарегистрирован https://github.com/docker/docker/issues/10176 , и таков способ обхода - небезопасный
    volumes:
     - /volume1/docker/1c/pg_sql:/var/lib/postgresql/data
    expose:
     - "5432"
    environment:
     - POSTGRES_PASSWORD=**
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    volumes:
     - /volume1/docker/1c/elasticsearch/data:/usr/share/elasticsearch/data
     - /volume1/docker/1c/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    expose:
     - "9200"
     - "9300"