version: '2'
services:
  apache:
    build:
      dockerfile: ./apache/Dockerfile
      context: .
    container_name: apache
    hostname: apache
    restart: always
    ports:
     - "80:80"
    volumes:
     - /vol1/docker/1c/apache_conf:/usr/local/apache2/conf/1c #сюда будем складывать файлы публикаций баз
    depends_on:
      - ones
  ones:
    build:
      dockerfile: ./ones/Dockerfile
      context: .
    container_name: ones
    hostname: ones
    restart: always
    ports:
     - "1540-1541:1540-1541"
     - "1560-1591:1560-1591"
    volumes:
     - /vol1/docker/1c/data:/root/.1cv8
     - /vol1/docker/1c/logs:/var/log/1c
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: temrdm/1c_postgres
    container_name: postgres
    hostname: postgres
    restart: always
# Если контейнер с postgresql не стартует и выдает ошибку про shmmax в sysctl, значит, это баг докера.
# он зарегистрирован https://github.com/docker/docker/issues/10176
# следующая команда "ipc: host" позволяет пофиксить его, но дает контейнеру доступ к процессам хоста, что небезопасно. 
# есть способы и надежнее, но уже не до того
    ipc: host
    volumes:
     - /vol1/docker/1c/pg_sql:/var/lib/postgresql/data
    expose:
     - "5432"
    environment:
     - POSTGRES_PASSWORD=**
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    volumes:
     - /vol1/docker/1c/elasticsearch/data:/usr/share/elasticsearch/data
     - /vol1/docker/1c/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    expose:
     - "9200"
     - "9300"